### PR TITLE
Update classes

### PR DESCRIPTION
**Pull request by KingGamingYT**
Updated the css classes due to discord's complete reroll of them from their module-restructuring update on 10-24-2023 
The plugin itself may need fixes in the js department to function properly again, I can't confirm this until BetterDiscord is fixed up to work with discord's changes fully.

### CODE REVIEW

**Comment by Tanza3D** [comment]
this plugin hasn't worked for a long time so i'll be surprised if this fixes it but i'll check as soon as betterdiscord works

**Comment by KingGamingYT** [comment]
> this plugin hasn't worked for a long time so i'll be surprised if this fixes it but i'll check as soon as betterdiscord works

I found that it worked up until discord's breaking changes two days ago for me, both un-cropping the images and de-mosaicing them, the only thing it didn't do was size them down (because newer image previews are like 20% bigger depending on image size)

Edit: Currently, however, this change only makes it so images are no longer grouped, and are formatted like they used to. They are still cropped, which either needs to be fixed through the js or it'll be fixed automatically when BetterDiscord is fixed. If BetterDiscord patches don't fix it further, I'll look into repairing the js as well.

**Comment by KingGamingYT** [comment]
After some further fixes, the plugin is in working order, however, there are some oddities which I haven't figured out how to fix yet:

- Some images will vary in size depending on which order you send them in and how many images are in the message
- Some images (I've especially observed this on ones with short heights) will have tons of dead space above and below the image, making a massive gap (screenshot included) when posted as part of a message containing other images
- Some embeds will still be slightly cut off vertically and/or horizontally
- Formatting breaks and images re-crop themselves if CTRL +/- is used, but will readjust themselves correctly if you switch to another channel and back
image

Edit: Sending 3 images will sometimes result in the bottom two images still being displayed horizontally, I have no idea why
image
Images can also be either way undercropped (like in the first image) or slightly overcropped (like in the second), it's so weird
Edit 2: Fixed the overcropping in the second image by not making it force height either, same as width

**Comment by KingGamingYT** [comment]
anything I changed after the last commit before I go to sleep is in the above commit

**Comment by KingGamingYT** [comment]
Some stuff has decided to break since my last commit, I've been working on it. I'll open another pull request when I feel like I've made it work as it should.

**Comment by Tanza3D** [comment]
sounds good, thanks for working on this a bit :smile:

**Pull request merged**
